module.exports =  [
  {
    displayName: 'Earth',
    internalName: 'earth_porn_reddit',
    sourceLabel: 'r/EarthPorn',
    description: 'EarthPorn is your community of landscape photographers and those who appreciate the natural beauty of our home planet.',
    endpoint: 'https://www.reddit.com/r/EarthPorn.json',
    isFollowing: true,
  },
  {
    displayName: 'Space',
    internalName: 'space_porn_reddit',
    sourceLabel: 'r/SpacePorn',
    description: 'SpacePorn is a subreddit devoted to high-quality images of space. As long as the focus of the image is of the stars or related to space in some way then it is allowed. This includes artwork as well as photography.',
    endpoint: 'https://www.reddit.com/r/spaceporn/.json',
    isFollowing: true,
  },
  {
    displayName: 'Mountains',
    internalName: 'mountains_reddit',
    sourceLabel: 'r/Mountains',
    description: 'A subreddit for discussing all things related to climbing, mountaineering, geology, geography, etc. Anything mountain related goes here.',
    endpoint: 'https://www.reddit.com/r/mountains.json',
    isFollowing: true,
  },
  {
    displayName: 'I Took A Picture',
    internalName: 'i_took_a_picture_reddit',
    sourceLabel: 'r/itookapicture',
    description: 'A subreddit about photography techniques and styles. Post your work here to ask for critique, or browse the submissions and learn how photography techniques are achieved.',
    endpoint: 'https://www.reddit.com/r/itookapicture.json',
    isFollowing: false,
  },
  {
    displayName: 'Seascapes',
    internalName: 'seascapes_reddit',
    sourceLabel: 'r/Seascapes',
    description: 'A subreddit dedicated to pictures of oceans, seas, and other large bodies of water.',
    endpoint: 'https://www.reddit.com/r/seascapes.json',
    isFollowing: false,
  },
  {
    displayName: 'Art',
    internalName: 'art_reddit',
    sourceLabel: 'r/Art',
    description: 'This is a subreddit about art. We do not support the reddit redesign. It is horrible and the admins have ignored our feedback. Please do not use it. Go to your preferences and enable old reddit as your default experience.',
    endpoint: 'https://www.reddit.com/r/Art.json',
    isFollowing: false,
  },
];
